### ISSUE TITLE
Adding a widget to the Administrators group does not add the widget to the user

### ISSUE THREAD

**Issue by mparizernc** [ozoneplatform/owf-framework#54]
Steps:

1. Add a widget to the Admins group 
2. As an OWF Admin verify that it does not show in the App Components
3. Add the OWF Admin directly to the OWF Admins group 
4. The widget appears
5. If you remove the widget from the group it does not get removed from the Admin user

You should able to add and remove widgets to an admin user through the Admin group directly without having to add the user to the group.

**Comment by rpokorny** [comment]
Any admin should already automatically be part of the Admin group.  Are you saying that this isn't the case or that they are, but aren't getting widgets, and re-adding them to the group fixes the problem?

**Comment by mparizernc** [comment]
I am saying it appears they are part of the group because they have access to the Admin features, but aren't getting the widgets. Re-adding them to the group appears to fix that.  Also when the widget is removed from the group the widget is not removed from the Admin user.

**Comment by mparizernc** [comment]
This is happening with Apps/Stacks as well.

**Comment by ruckc** [comment]
I ran into this if the widget type isn't 'standard'.

**Comment by qotho** [comment]
I'm seeing what I think is the same or a related issue.  My custom security plugin pulls the groups for a user correctly, and they are shown as members of the proper groups in OWF, but they don't get the widgets they should get.

This is because there are no person_widget_definition records created for the user.  If I manually remove any group through the OWF admin UI, and re-add it, the widgets show up.  I compared the person_widget_definition table before and after doing this, and the person_widget_definition records aren't there before, and they get added after I remove and re-add the group.  Records seem to be added for all widgets, not just those associated with the group I modified.

**Comment by qotho** [comment]
I think this might be related to changes in ConfigController.groovy.  In 7.14.2, it used to call PersonWidgetDefinitionService.list, which cleans up PersonWidgetDefinitions, including adding new ones.  The changes were made in the following commit in DI2E:

https://stash.di2e.net/projects/OWFGOSS/repos/aml-owf/commits/546845b03a246551a0fddf6cde06d78ec93c5293#grails-app/controllers/ozone/owf/grails/controllers/ConfigController.groovy

**Comment by stephanieerin** [comment]
@qotho I checked out that area of the ConfigController and I think you're on to something but that's not the only place we used to do this. Additionally, weirdly enough this bug is only reproducible in databases other than H2. Leads me to believe some part of this query process is incompatible with other syntax or something.

**Comment by qotho** [comment]
It looks like the problem is generally related to the "sync" related changes.  The user's groups are updated on login in SecurityFilters.  In 7.14.2, there used to be a call in ConfigController that caused the person_widget_definition records to be updated for the user, based on their updated group membership.  This functionality was moved in the changes I referred to before to consolidate user synchronization actions.

The problem is that the call in ConfigController was never replaced.  So even though SecurityFilters updates a user's group memberships, nothing syncs the person_widget_definition records after login.  Manually adding or removing a group for the user causes a sync to happen.

I added a call to "AccountService.sync", in SecurityFilters, to force the person_widget_definition records to be synchronized if a user's group memberships have changed.  This seems to fix my issue.  I'm not sure if it also addresses the original admin group issue.  Here is a link to the change:

https://github.com/qotho/owf-framework/commit/8af7be42a5a7cb45f9f9e62a5f4340ededfe4b2e

**Comment by stephanieerin** [comment]
The stub of the problem is that it was looking to sync users in the admin group based on their role as admin, which wasn’t getting set correctly. See the latest changes and let me know if this fixes the issues you were seeing as well as the one we were experiencing.

Stephanie

**Comment by qotho** [comment]
I tried the new changes and unfortunately my issue is still happening.  If I alter a user's group membership outside of OWF (like LDAP), the membership change is detected and made by SecurityFilters.  Meaning, if I go into the "Users" widget and look at the user's groups, they are correct, but the user does not get the widgets associated with a newly added group or lose them when a group is removed from the user.  This is because SecurityFilters does not trigger a sync call to update the person_widget_definition records.

At this point, this seems like a different issue from this one.  Do you want me to open a separate issue?

**Comment by stephanieerin** [comment]
Yeah, open a separate bug for this. I’ll take a look at the work you did but I don’t know that this is going to make it to 7.16.1.

Stephanie
